
// =====================================================
// 夏商西周 数据 (自动生成)
// =====================================================

// --- 朝代 ---
{
  id: 201,
  name: '夏商西周',
  english_name: 'Xia-Shang-Western Zhou',
  start_year: -2070,
  end_year: -771,
  summary: '中国历史上的青铜时代，夏朝建立了中国第一个王朝，商朝创造了灿烂的青铜文明，西周实行分封制和宗法制，奠定了中国古代政治制度的基础。',
  capital: '阳城/亳/殷/镐京',
  population: '约数百万',
  duration: '约1300年',
  representative_buildings: ["二里头遗址","殷墟","周原遗址","丰镐遗址"],
  characteristics: {"politics":80,"culture":85,"military":75,"technology":82,"openness":70}
},

// --- 夏商西周人物 (65人) ---
{
    id: 201001,
    name: '启',
    dynasty: '夏商西周',
    summary: '大禹之子，继承禹的权力，建立夏朝早期统治秩序，传统上被视为世袭王位的重要转折人物。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%90%AF%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '阳翟（传说）',
    occupations: ["夏朝建立者"],
    related_people: [{"name":"太康","relation":"kinship","influence":75}],
    influence: 95,
    dimension_scores: {"historical_influence":95,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201002,
    name: '太康',
    dynasty: '夏商西周',
    summary: '夏启之后的君主，传统史书中的“太康失国”成为夏朝早期政治危机的重要象征。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%A4%AA%E5%BA%B7%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: -2100,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '夏都地区',
    occupations: ["夏王"],
    related_people: [{"name":"启","relation":"kinship","influence":75},{"name":"仲康","relation":"kinship","influence":75},{"name":"后羿","relation":"hostile","influence":75}],
    related_events: [{"name":"太康失国","role":"失势者"}],
    influence: 78,
    dimension_scores: {"historical_influence":78,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201003,
    name: '仲康',
    dynasty: '夏商西周',
    summary: '夏朝君主，处于太康失国之后的王权恢复阶段。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E4%BB%B2%E5%BA%B7%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '夏',
    occupations: ["夏王"],
    related_people: [{"name":"太康","relation":"kinship","influence":75}],
    influence: 72,
    dimension_scores: {"historical_influence":72,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201004,
    name: '少康',
    dynasty: '夏商西周',
    summary: '夏朝中兴的重要君主，在寒浞势力控制下恢复夏王室，被称为“少康中兴”。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%B0%91%E5%BA%B7%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '有仍（传统说法）',
    occupations: ["夏王"],
    related_people: [{"name":"寒浞","relation":"hostile","influence":75},{"name":"伯靡","relation":"lord_vassal","influence":75},{"name":"女艾","relation":"lord_vassal","influence":75}],
    related_events: [{"name":"少康中兴","role":"中兴者"}],
    influence: 90,
    dimension_scores: {"historical_influence":90,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201005,
    name: '夏桀',
    dynasty: '夏商西周',
    summary: '夏朝末代君主，传统史书将其描绘为暴政代表，最终在商汤攻伐下失去王位。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%A4%8F%E6%A1%80%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '夏',
    occupations: ["夏朝末代君主"],
    related_people: [{"name":"关龙逢","relation":"lord_vassal","influence":75},{"name":"妺喜","relation":"support","influence":75},{"name":"商汤","relation":"hostile","influence":75}],
    related_events: [{"name":"夏桀暴政","role":"统治者"},{"name":"商汤灭夏","role":"失败方"}],
    influence: 92,
    dimension_scores: {"historical_influence":92,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201006,
    name: '商汤',
    dynasty: '夏商西周',
    summary: '商族首领，通过征伐夏桀建立商朝，是夏商更替的重要人物。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%95%86%E6%B1%A4%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '亳',
    occupations: ["商王朝建立者"],
    related_people: [{"name":"夏桀","relation":"hostile","influence":75},{"name":"伊尹","relation":"lord_vassal","influence":75},{"name":"仲虺","relation":"lord_vassal","influence":75}],
    related_events: [{"name":"商汤灭夏","role":"胜利方"}],
    influence: 99,
    dimension_scores: {"historical_influence":99,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201007,
    name: '太甲',
    dynasty: '夏商西周',
    summary: '商汤之后的重要商王，传统文献记载其曾因失德被伊尹放逐，后重新执政。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%A4%AA%E7%94%B2%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '亳',
    occupations: ["商王"],
    related_people: [{"name":"伊尹","relation":"lord_vassal","influence":75}],
    influence: 82,
    dimension_scores: {"historical_influence":82,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201008,
    name: '太戊',
    dynasty: '夏商西周',
    summary: '商朝中期的重要君主，传统上被视为商朝中兴时期代表人物。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%A4%AA%E6%88%8A%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '亳',
    occupations: ["商王"],
    influence: 88,
    dimension_scores: {"historical_influence":88,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201009,
    name: '盘庚',
    dynasty: '夏商西周',
    summary: '商朝重要君主，通过迁都于殷稳定商朝统治，由此形成长期稳定的政治中心。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E7%9B%98%E5%BA%9A%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '奄、殷',
    occupations: ["商王"],
    related_people: [{"name":"祖甲","relation":"kinship","influence":75}],
    related_events: [{"name":"盘庚迁殷","role":"主导者"}],
    influence: 94,
    dimension_scores: {"historical_influence":94,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201010,
    name: '武丁',
    dynasty: '夏商西周',
    summary: '商朝后期著名君主，任用傅说、妇好等人才，开创“武丁中兴”。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E6%AD%A6%E4%B8%81%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '商',
    occupations: ["商王"],
    related_people: [{"name":"妇好","relation":"kinship","influence":75},{"name":"傅说","relation":"lord_vassal","influence":75},{"name":"甘盘","relation":"lord_vassal","influence":75},{"name":"祖己","relation":"support","influence":75}],
    related_events: [{"name":"武丁中兴","role":"主导者"},{"name":"妇好征伐","role":"统治者"},{"name":"商王对外征伐","role":"统治者"}],
    influence: 98,
    dimension_scores: {"historical_influence":98,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201011,
    name: '妇好',
    dynasty: '夏商西周',
    summary: '武丁时期的重要王后，同时承担祭祀与军事职责，甲骨文和妇好墓为研究商代社会提供重要材料。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%A6%87%E5%A5%BD%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '军事人物',
    level: 1,
    birth_place: '商',
    occupations: ["王后、军事人物"],
    related_people: [{"name":"武丁","relation":"kinship","influence":75},{"name":"傅说","relation":"friend","influence":75}],
    related_events: [{"name":"武丁中兴","role":"重要人物"},{"name":"妇好征伐","role":"军事人物"}],
    influence: 97,
    dimension_scores: {"historical_influence":97,"relation_activity":82,"professional_1":90,"professional_2":85,"professional_3":80},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201012,
    name: '祖甲',
    dynasty: '夏商西周',
    summary: '商朝后期君主，传统文献对其政治和礼制改革有相关记载。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E7%A5%96%E7%94%B2%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '商',
    occupations: ["商王"],
    related_people: [{"name":"盘庚","relation":"kinship","influence":75}],
    influence: 83,
    dimension_scores: {"historical_influence":83,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201013,
    name: '帝乙',
    dynasty: '夏商西周',
    summary: '商朝末期君主，处于商王朝逐渐衰落阶段，为帝辛之父。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%B8%9D%E4%B9%99%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '商',
    occupations: ["商王"],
    related_people: [{"name":"帝辛","relation":"kinship","influence":75}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201014,
    name: '帝辛',
    dynasty: '夏商西周',
    summary: '商朝末代君主，即传统所称纣王，最终在周武王伐纣后失去统治。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%B8%9D%E8%BE%9B%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '朝歌',
    occupations: ["商朝末代君主"],
    related_people: [{"name":"帝乙","relation":"kinship","influence":75},{"name":"比干","relation":"kinship","influence":75},{"name":"箕子","relation":"support","influence":75},{"name":"微子启","relation":"kinship","influence":75}],
    related_events: [{"name":"商末政治危机","role":"统治者"},{"name":"牧野之战","role":"失败方"}],
    influence: 98,
    dimension_scores: {"historical_influence":98,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201015,
    name: '周太王',
    dynasty: '夏商西周',
    summary: '周族早期重要首领，推动周族发展并迁居岐山一带，为周族兴起奠定基础。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%91%A8%E5%A4%AA%E7%8E%8B%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '邠地',
    occupations: ["周族首领"],
    related_people: [{"name":"王季","relation":"kinship","influence":75}],
    influence: 86,
    dimension_scores: {"historical_influence":86,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201016,
    name: '王季',
    dynasty: '夏商西周',
    summary: '周文王之父，继承周族领导权，为周族后续发展创造条件。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E7%8E%8B%E5%AD%A3%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '岐山',
    occupations: ["周族首领"],
    related_people: [{"name":"周太王","relation":"kinship","influence":75},{"name":"周文王","relation":"kinship","influence":75}],
    influence: 82,
    dimension_scores: {"historical_influence":82,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201017,
    name: '周文王',
    dynasty: '夏商西周',
    summary: '周武王之父，周族兴起的重要领导者，推动政治与军事力量发展。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%91%A8%E6%96%87%E7%8E%8B%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '岐山',
    occupations: ["周族首领"],
    related_people: [{"name":"王季","relation":"kinship","influence":75},{"name":"周武王","relation":"kinship","influence":75},{"name":"周公旦","relation":"kinship","influence":75},{"name":"姜子牙","relation":"lord_vassal","influence":75}],
    influence: 99,
    dimension_scores: {"historical_influence":99,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201018,
    name: '周武王',
    dynasty: '夏商西周',
    summary: '周文王之子，联合诸侯伐商并在牧野之战击败商军，建立周朝。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%91%A8%E6%AD%A6%E7%8E%8B%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '镐京',
    occupations: ["西周建立者"],
    related_people: [{"name":"周文王","relation":"kinship","influence":75},{"name":"周公旦","relation":"kinship","influence":75},{"name":"周成王","relation":"kinship","influence":75},{"name":"姜子牙","relation":"lord_vassal","influence":75},{"name":"召公奭","relation":"lord_vassal","influence":75},{"name":"康叔封","relation":"kinship","influence":75}],
    related_events: [{"name":"牧野之战","role":"胜利方"},{"name":"分封制","role":"制度建立者"}],
    influence: 100,
    dimension_scores: {"historical_influence":100,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201019,
    name: '周成王',
    dynasty: '夏商西周',
    summary: '周武王之子，在周公辅政下完成周初政治秩序建设。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%91%A8%E6%88%90%E7%8E%8B%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '镐京',
    occupations: ["周王"],
    related_people: [{"name":"周武王","relation":"kinship","influence":75},{"name":"周公旦","relation":"lord_vassal","influence":75},{"name":"伯禽","relation":"support","influence":75},{"name":"周康王","relation":"support","influence":75}],
    related_events: [{"name":"成康之治","role":"统治者"},{"name":"制礼作乐","role":"统治者"}],
    influence: 94,
    dimension_scores: {"historical_influence":94,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201020,
    name: '周康王',
    dynasty: '夏商西周',
    summary: '西周早期君主，与周成王共同构成传统所称“成康之治”的重要阶段。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%91%A8%E5%BA%B7%E7%8E%8B%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '镐京',
    occupations: ["周王"],
    related_people: [{"name":"周成王","relation":"support","influence":75}],
    related_events: [{"name":"成康之治","role":"统治者"}],
    influence: 92,
    dimension_scores: {"historical_influence":92,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201021,
    name: '周穆王',
    dynasty: '夏商西周',
    summary: '西周中期重要君主，传统文献记载其曾进行西征，与西方诸族交往。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%91%A8%E7%A9%86%E7%8E%8B%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '镐京',
    occupations: ["周王"],
    related_people: [{"name":"周厉王","relation":"support","influence":75}],
    influence: 90,
    dimension_scores: {"historical_influence":90,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201022,
    name: '周厉王',
    dynasty: '夏商西周',
    summary: '西周后期君主，因政治矛盾激化导致国人暴动，最终失去王位。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%91%A8%E5%8E%89%E7%8E%8B%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '镐京',
    occupations: ["周王"],
    related_people: [{"name":"荣夷公","relation":"lord_vassal","influence":75},{"name":"召穆公","relation":"lord_vassal","influence":75},{"name":"周穆王","relation":"support","influence":75},{"name":"周宣王","relation":"kinship","influence":75}],
    related_events: [{"name":"国人暴动","role":"被驱逐者"}],
    influence: 93,
    dimension_scores: {"historical_influence":93,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201023,
    name: '周宣王',
    dynasty: '夏商西周',
    summary: '西周后期君主，采取一系列军事和政治措施，使周王朝出现短暂复兴。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%91%A8%E5%AE%A3%E7%8E%8B%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '镐京',
    occupations: ["周王"],
    related_people: [{"name":"尹吉甫","relation":"lord_vassal","influence":75},{"name":"方叔","relation":"lord_vassal","influence":75},{"name":"召虎","relation":"lord_vassal","influence":75},{"name":"周幽王","relation":"kinship","influence":75},{"name":"周厉王","relation":"kinship","influence":75}],
    related_events: [{"name":"宣王中兴","role":"主导者"}],
    influence: 94,
    dimension_scores: {"historical_influence":94,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201024,
    name: '周幽王',
    dynasty: '夏商西周',
    summary: '西周末代君主，周王室内部矛盾和犬戎入侵最终导致西周灭亡。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%91%A8%E5%B9%BD%E7%8E%8B%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 1,
    birth_place: '镐京',
    occupations: ["西周末代君主"],
    related_people: [{"name":"褒姒","relation":"kinship","influence":75},{"name":"申侯","relation":"hostile","influence":75},{"name":"周宣王","relation":"kinship","influence":75}],
    related_events: [{"name":"犬戎攻周","role":"失败方"},{"name":"西周灭亡","role":"末代君主"}],
    influence: 98,
    dimension_scores: {"historical_influence":98,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 201025,
    name: '周公旦',
    dynasty: '夏商西周',
    summary: '周武王之弟，武王死后辅佐成王，平定三监之乱并参与周初制度建设，是周代政治文化的重要奠基人物。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%91%A8%E5%85%AC%E6%97%A6%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '政治人物',
    level: 1,
    birth_place: '周',
    occupations: ["周初政治家"],
    related_people: [{"name":"周文王","relation":"kinship","influence":75},{"name":"周武王","relation":"kinship","influence":75},{"name":"周成王","relation":"lord_vassal","influence":75},{"name":"管叔鲜","relation":"hostile","influence":75},{"name":"蔡叔度","relation":"hostile","influence":75},{"name":"霍叔处","relation":"hostile","influence":75},{"name":"武庚","relation":"hostile","influence":75},{"name":"伯禽","relation":"kinship","influence":75}],
    related_events: [{"name":"牧野之战","role":"宗室成员"},{"name":"周公东征","role":"主导者"},{"name":"成康之治","role":"辅政者"},{"name":"制礼作乐","role":"制度建设者"},{"name":"分封制","role":"制度推动者"}],
    influence: 100,
    dimension_scores: {"historical_influence":100,"relation_activity":85,"professional_1":85,"professional_2":90,"professional_3":82},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202026,
    name: '后羿',
    dynasty: '夏商西周',
    summary: '夏朝早期政治传说中的重要人物，相传掌握夏政，并在太康失国后形成独立的政治势力。后羿后来被寒浞取代，其故事成为夏初政治动荡的重要传说。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%90%8E%E7%BE%BF%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '军事人物',
    level: 2,
    occupations: ["部落首领、军事人物"],
    related_people: [{"name":"太康","relation":"hostile","influence":75},{"name":"寒浞","relation":"lord_vassal","influence":75}],
    related_events: [{"name":"太康失国","role":"政权掌握者"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":82,"professional_1":90,"professional_2":85,"professional_3":80},
    story: {"title":"后羿的故事","content":"后羿，是中国历史上重要的历史人物。夏朝早期政治传说中的重要人物，相传掌握夏政，并在太康失国后形成独立的政治势力。后羿后来被寒浞取代，其故事成为夏初政治动荡的重要传说。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%90%8E%E7%BE%BF%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202027,
    name: '寒浞',
    dynasty: '夏商西周',
    summary: '相传后羿掌权后，寒浞逐渐取得其势力，最终杀死后羿并掌握夏朝政权。后来少康重新组织力量，使夏王室复兴。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%AF%92%E6%B5%9E%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 2,
    occupations: ["部落首领、政治人物"],
    related_people: [{"name":"后羿","relation":"lord_vassal","influence":75},{"name":"少康","relation":"hostile","influence":75}],
    related_events: [{"name":"少康中兴","role":"对立者"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    story: {"title":"寒浞的故事","content":"寒浞，是中国历史上重要的历史人物。相传后羿掌权后，寒浞逐渐取得其势力，最终杀死后羿并掌握夏朝政权。后来少康重新组织力量，使夏王室复兴。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%AF%92%E6%B5%9E%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202028,
    name: '女艾',
    dynasty: '夏商西周',
    summary: '传统记载中的女性人物，相传受到少康派遣，深入寒浞势力内部获取情报，为少康复国创造条件，是中国早期历史传说中少见的女性政治人物形象。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%A5%B3%E8%89%BE%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '政治人物',
    level: 2,
    occupations: ["少康谋臣"],
    related_people: [{"name":"少康","relation":"lord_vassal","influence":75}],
    related_events: [{"name":"少康中兴","role":"谋臣"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":85,"professional_1":85,"professional_2":90,"professional_3":82},
    story: {"title":"女艾的故事","content":"女艾，是中国历史上重要的历史人物。传统记载中的女性人物，相传受到少康派遣，深入寒浞势力内部获取情报，为少康复国创造条件，是中国早期历史传说中少见的女性政治人物形象。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%A5%B3%E8%89%BE%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202029,
    name: '伯靡',
    dynasty: '夏商西周',
    summary: '夏王室的重要支持者，相传在少康失国后仍坚持支持夏王室，并协助少康积蓄力量、恢复夏朝政权。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E4%BC%AF%E9%9D%A1%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '政治人物',
    level: 2,
    occupations: ["夏臣"],
    related_people: [{"name":"少康","relation":"lord_vassal","influence":75}],
    related_events: [{"name":"少康中兴","role":"支持者"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":85,"professional_1":85,"professional_2":90,"professional_3":82},
    story: {"title":"伯靡的故事","content":"伯靡，是中国历史上重要的历史人物。夏王室的重要支持者，相传在少康失国后仍坚持支持夏王室，并协助少康积蓄力量、恢复夏朝政权。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E4%BC%AF%E9%9D%A1%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202030,
    name: '关龙逢',
    dynasty: '夏商西周',
    summary: '传统文献中的忠臣形象，相传因直言劝谏夏桀、反对其暴政而遭杀害，后世常将其视为忠臣直谏的代表。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%85%B3%E9%BE%99%E9%80%A2%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '政治人物',
    level: 2,
    occupations: ["夏朝大臣"],
    related_people: [{"name":"夏桀","relation":"lord_vassal","influence":75}],
    related_events: [{"name":"夏桀暴政","role":"进谏者"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":85,"professional_1":85,"professional_2":90,"professional_3":82},
    story: {"title":"关龙逢的故事","content":"关龙逢，是中国历史上重要的历史人物。传统文献中的忠臣形象，相传因直言劝谏夏桀、反对其暴政而遭杀害，后世常将其视为忠臣直谏的代表。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%85%B3%E9%BE%99%E9%80%A2%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202031,
    name: '妺喜',
    dynasty: '夏商西周',
    summary: '传统历史叙事中的夏末女性人物，与夏桀统治和夏朝灭亡的故事联系在一起。其形象经过后世文学与民间叙事不断加工，具有较强的传说色彩。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%A6%BA%E5%96%9C%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '文化人物',
    level: 2,
    occupations: ["夏桀宠妃"],
    related_people: [{"name":"夏桀","relation":"support","influence":75}],
    related_events: [{"name":"夏桀暴政","role":"宫廷人物"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":78,"professional_1":80,"professional_2":92,"professional_3":88},
    story: {"title":"妺喜的故事","content":"妺喜，是中国历史上重要的历史人物。传统历史叙事中的夏末女性人物，与夏桀统治和夏朝灭亡的故事联系在一起。其形象经过后世文学与民间叙事不断加工，具有较强的传说色彩。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%A6%BA%E5%96%9C%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202032,
    name: '费昌',
    dynasty: '夏商西周',
    summary: '传统记载中的夏商之际人物，相传由夏转向商，后来成为商汤一方的重要人物，是观察夏商政治力量转换的一个人物节点。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E8%B4%B9%E6%98%8C%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '政治人物',
    level: 2,
    occupations: ["夏末商初人物"],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":85,"professional_1":85,"professional_2":90,"professional_3":82},
    story: {"title":"费昌的故事","content":"费昌，是中国历史上重要的历史人物。传统记载中的夏商之际人物，相传由夏转向商，后来成为商汤一方的重要人物，是观察夏商政治力量转换的一个人物节点。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E8%B4%B9%E6%98%8C%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202033,
    name: '昆吾',
    dynasty: '夏商西周',
    summary: '夏末重要方国势力的代表人物，传统记载中与夏桀及商汤灭夏的政治格局有关，可用于展示夏末诸侯势力与王朝更替之间的关系。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E6%98%86%E5%90%BE%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 2,
    occupations: ["诸侯、方国首领"],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    story: {"title":"昆吾的故事","content":"昆吾，是中国历史上重要的历史人物。夏末重要方国势力的代表人物，传统记载中与夏桀及商汤灭夏的政治格局有关，可用于展示夏末诸侯势力与王朝更替之间的关系。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E6%98%86%E5%90%BE%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202034,
    name: '皋陶',
    dynasty: '夏商西周',
    summary: '传说中的早期政治人物，与尧、舜、禹时期的政治秩序和司法传统密切相关。其形象常被后世视为中国早期司法制度的重要象征。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E7%9A%8B%E9%99%B6%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '政治人物',
    level: 2,
    occupations: ["司法官、政治人物"],
    related_people: [{"name":"伯益","relation":"friend","influence":75}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":85,"professional_1":85,"professional_2":90,"professional_3":82},
    story: {"title":"皋陶的故事","content":"皋陶，是中国历史上重要的历史人物。传说中的早期政治人物，与尧、舜、禹时期的政治秩序和司法传统密切相关。其形象常被后世视为中国早期司法制度的重要象征。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E7%9A%8B%E9%99%B6%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202035,
    name: '伯益',
    dynasty: '夏商西周',
    summary: '禹时期的重要辅臣，传统记载中参与治水和山泽管理，并与夏初政治传承有关。其人物形象能够连接上古时代与夏朝早期的政治发展。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E4%BC%AF%E7%9B%8A%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '政治人物',
    level: 2,
    occupations: ["辅臣"],
    related_people: [{"name":"皋陶","relation":"friend","influence":75}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":85,"professional_1":85,"professional_2":90,"professional_3":82},
    story: {"title":"伯益的故事","content":"伯益，是中国历史上重要的历史人物。禹时期的重要辅臣，传统记载中参与治水和山泽管理，并与夏初政治传承有关。其人物形象能够连接上古时代与夏朝早期的政治发展。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E4%BC%AF%E7%9B%8A%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202036,
    name: '伊尹',
    dynasty: '夏商西周',
    summary: '商汤的重要辅臣，传统文献中被认为参与商汤灭夏，并在商朝建立后辅佐政权，是商初政治治理的重要人物。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E4%BC%8A%E5%B0%B9%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '政治人物',
    level: 2,
    occupations: ["商汤辅臣"],
    related_people: [{"name":"商汤","relation":"lord_vassal","influence":75},{"name":"太甲","relation":"lord_vassal","influence":75}],
    related_events: [{"name":"商汤灭夏","role":"辅政者"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":85,"professional_1":85,"professional_2":90,"professional_3":82},
    story: {"title":"伊尹的故事","content":"伊尹，是中国历史上重要的历史人物。商汤的重要辅臣，传统文献中被认为参与商汤灭夏，并在商朝建立后辅佐政权，是商初政治治理的重要人物。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E4%BC%8A%E5%B0%B9%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202037,
    name: '仲虺',
    dynasty: '夏商西周',
    summary: '商汤时期的重要辅臣，传统文献中与商汤灭夏以及商初政治建设有关，是商汤政治集团的重要人物。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E4%BB%B2%E8%99%BA%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '政治人物',
    level: 2,
    occupations: ["商汤辅臣"],
    related_people: [{"name":"商汤","relation":"lord_vassal","influence":75}],
    related_events: [{"name":"商汤灭夏","role":"辅政者"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":85,"professional_1":85,"professional_2":90,"professional_3":82},
    story: {"title":"仲虺的故事","content":"仲虺，是中国历史上重要的历史人物。商汤时期的重要辅臣，传统文献中与商汤灭夏以及商初政治建设有关，是商汤政治集团的重要人物。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E4%BB%B2%E8%99%BA%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202038,
    name: '葛伯',
    dynasty: '夏商西周',
    summary: '商汤灭夏过程中相关方国的首领，传统记载中因与商汤发生冲突而成为商汤征伐体系中的重要人物。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E8%91%9B%E4%BC%AF%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 2,
    occupations: ["方国首领"],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    story: {"title":"葛伯的故事","content":"葛伯，是中国历史上重要的历史人物。商汤灭夏过程中相关方国的首领，传统记载中因与商汤发生冲突而成为商汤征伐体系中的重要人物。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E8%91%9B%E4%BC%AF%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202039,
    name: '巫咸',
    dynasty: '夏商西周',
    summary: '商代重要巫者和政治人物，传统文献中与王权、祭祀和占卜活动有关，体现了商代政治与宗教高度结合的社会特征。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%B7%AB%E5%92%B8%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '思想家',
    level: 2,
    occupations: ["巫师、政治人物"],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":75,"professional_1":85,"professional_2":90,"professional_3":95},
    story: {"title":"巫咸的故事","content":"巫咸，是中国历史上重要的历史人物。商代重要巫者和政治人物，传统文献中与王权、祭祀和占卜活动有关，体现了商代政治与宗教高度结合的社会特征。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%B7%AB%E5%92%B8%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202040,
    name: '甘盘',
    dynasty: '夏商西周',
    summary: '武丁时期的重要臣僚，传统记载中与武丁早期政治经历有关，是武丁任用贤臣、整顿政治的重要人物之一。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E7%94%98%E7%9B%98%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '政治人物',
    level: 2,
    occupations: ["武丁辅臣"],
    related_people: [{"name":"武丁","relation":"lord_vassal","influence":75}],
    related_events: [{"name":"武丁中兴","role":"辅政者"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":85,"professional_1":85,"professional_2":90,"professional_3":82},
    story: {"title":"甘盘的故事","content":"甘盘，是中国历史上重要的历史人物。武丁时期的重要臣僚，传统记载中与武丁早期政治经历有关，是武丁任用贤臣、整顿政治的重要人物之一。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E7%94%98%E7%9B%98%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202041,
    name: '傅说',
    dynasty: '夏商西周',
    summary: '武丁时期的重要政治家，传统记载中武丁通过梦兆寻找并任用傅说，使其成为辅佐自己的重要大臣，是武丁中兴的重要人物。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%82%85%E8%AF%B4%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '政治人物',
    level: 2,
    occupations: ["武丁辅臣"],
    related_people: [{"name":"武丁","relation":"lord_vassal","influence":75},{"name":"妇好","relation":"friend","influence":75}],
    related_events: [{"name":"武丁中兴","role":"辅政者"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":85,"professional_1":85,"professional_2":90,"professional_3":82},
    story: {"title":"傅说的故事","content":"傅说，是中国历史上重要的历史人物。武丁时期的重要政治家，传统记载中武丁通过梦兆寻找并任用傅说，使其成为辅佐自己的重要大臣，是武丁中兴的重要人物。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%82%85%E8%AF%B4%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202042,
    name: '祖己',
    dynasty: '夏商西周',
    summary: '武丁时期的重要王室成员，传统文献中以劝谏武丁等事迹著称，其人物故事体现了商代王室内部政治与祭祀传统。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E7%A5%96%E5%B7%B1%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '政治人物',
    level: 2,
    occupations: ["商王室成员、政治人物"],
    related_people: [{"name":"武丁","relation":"support","influence":75}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":85,"professional_1":85,"professional_2":90,"professional_3":82},
    story: {"title":"祖己的故事","content":"祖己，是中国历史上重要的历史人物。武丁时期的重要王室成员，传统文献中以劝谏武丁等事迹著称，其人物故事体现了商代王室内部政治与祭祀传统。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E7%A5%96%E5%B7%B1%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202043,
    name: '微子启',
    dynasty: '夏商西周',
    summary: '帝辛的兄长，商末王室的重要人物。商朝灭亡后被周人封于宋，其经历连接了商亡、周初政治秩序与宋国建立。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%BE%AE%E5%AD%90%E5%90%AF%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '政治人物',
    level: 2,
    occupations: ["商王室成员"],
    related_people: [{"name":"帝辛","relation":"kinship","influence":75}],
    related_events: [{"name":"商末政治危机","role":"王室人物"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":85,"professional_1":85,"professional_2":90,"professional_3":82},
    story: {"title":"微子启的故事","content":"微子启，是中国历史上重要的历史人物。帝辛的兄长，商末王室的重要人物。商朝灭亡后被周人封于宋，其经历连接了商亡、周初政治秩序与宋国建立。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%BE%AE%E5%AD%90%E5%90%AF%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202044,
    name: '比干',
    dynasty: '夏商西周',
    summary: '商末重要大臣，传统记载中因忠谏帝辛而遭杀害，后世逐渐形成忠臣典范形象，是商末政治危机叙事的重要人物。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E6%AF%94%E5%B9%B2%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '政治人物',
    level: 2,
    occupations: ["商朝大臣"],
    related_people: [{"name":"帝辛","relation":"kinship","influence":75},{"name":"箕子","relation":"kinship","influence":75}],
    related_events: [{"name":"商末政治危机","role":"进谏者"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":85,"professional_1":85,"professional_2":90,"professional_3":82},
    story: {"title":"比干的故事","content":"比干，是中国历史上重要的历史人物。商末重要大臣，传统记载中因忠谏帝辛而遭杀害，后世逐渐形成忠臣典范形象，是商末政治危机叙事的重要人物。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E6%AF%94%E5%B9%B2%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202045,
    name: '箕子',
    dynasty: '夏商西周',
    summary: '商末王室成员，传统记载中曾向帝辛进谏。商亡后，其人物故事又与周初政治秩序以及箕子朝鲜传说联系在一起。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E7%AE%95%E5%AD%90%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '思想家',
    level: 2,
    occupations: ["商王室成员、政治人物"],
    related_people: [{"name":"帝辛","relation":"support","influence":75},{"name":"比干","relation":"kinship","influence":75}],
    related_events: [{"name":"商末政治危机","role":"王室人物"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":75,"professional_1":85,"professional_2":90,"professional_3":95},
    story: {"title":"箕子的故事","content":"箕子，是中国历史上重要的历史人物。商末王室成员，传统记载中曾向帝辛进谏。商亡后，其人物故事又与周初政治秩序以及箕子朝鲜传说联系在一起。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E7%AE%95%E5%AD%90%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202046,
    name: '妲己',
    dynasty: '夏商西周',
    summary: '商末历史叙事中的重要女性人物，传统文学与民间故事常将她与帝辛统治和商朝灭亡联系起来，但相关故事经过后世不断演绎，传说色彩较强。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%A6%B2%E5%B7%B1%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '文化人物',
    level: 2,
    occupations: ["帝辛宠妃"],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":78,"professional_1":80,"professional_2":92,"professional_3":88},
    story: {"title":"妲己的故事","content":"妲己，是中国历史上重要的历史人物。商末历史叙事中的重要女性人物，传统文学与民间故事常将她与帝辛统治和商朝灭亡联系起来，但相关故事经过后世不断演绎，传说色彩较强。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%A6%B2%E5%B7%B1%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202047,
    name: '飞廉',
    dynasty: '夏商西周',
    summary: '商末重要人物，传统记载中与帝辛统治及商周战争有关，是商末政治与军事集团中的代表人物之一。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E9%A3%9E%E5%BB%89%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '军事人物',
    level: 2,
    occupations: ["商末臣将"],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":82,"professional_1":90,"professional_2":85,"professional_3":80},
    story: {"title":"飞廉的故事","content":"飞廉，是中国历史上重要的历史人物。商末重要人物，传统记载中与帝辛统治及商周战争有关，是商末政治与军事集团中的代表人物之一。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E9%A3%9E%E5%BB%89%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202048,
    name: '太姒',
    dynasty: '夏商西周',
    summary: '周文王王后，传统文献中以贤德形象著称，是周初王室女性的重要代表。她与周文王、周武王以及周初王室传承之间具有密切关系。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%A4%AA%E5%A7%92%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '文化人物',
    level: 2,
    occupations: ["周文王王后"],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":78,"professional_1":80,"professional_2":92,"professional_3":88},
    story: {"title":"太姒的故事","content":"太姒，是中国历史上重要的历史人物。周文王王后，传统文献中以贤德形象著称，是周初王室女性的重要代表。她与周文王、周武王以及周初王室传承之间具有密切关系。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%A4%AA%E5%A7%92%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202049,
    name: '伯邑考',
    dynasty: '夏商西周',
    summary: '周文王长子，传统记载中与周文王、周武王及商纣王之间存在密切关系。其故事成为周初王室历史与传说的重要组成部分。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E4%BC%AF%E9%82%91%E8%80%83%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 2,
    occupations: ["周文王长子"],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    story: {"title":"伯邑考的故事","content":"伯邑考，是中国历史上重要的历史人物。周文王长子，传统记载中与周文王、周武王及商纣王之间存在密切关系。其故事成为周初王室历史与传说的重要组成部分。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E4%BC%AF%E9%82%91%E8%80%83%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202050,
    name: '姜子牙',
    dynasty: '夏商西周',
    summary: '周武王的重要辅臣和军事人物，传统上被称为太公望，参与伐商，并在周朝建立后受封齐国，是商周更替过程中最具代表性的辅臣之一。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%A7%9C%E5%AD%90%E7%89%99%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '军事人物',
    level: 2,
    occupations: ["周武王辅臣、军事家"],
    related_people: [{"name":"周文王","relation":"lord_vassal","influence":75},{"name":"周武王","relation":"lord_vassal","influence":75}],
    related_events: [{"name":"牧野之战","role":"重要将领"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":82,"professional_1":90,"professional_2":85,"professional_3":80},
    story: {"title":"姜子牙的故事","content":"姜子牙，是中国历史上重要的历史人物。周武王的重要辅臣和军事人物，传统上被称为太公望，参与伐商，并在周朝建立后受封齐国，是商周更替过程中最具代表性的辅臣之一。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%A7%9C%E5%AD%90%E7%89%99%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202051,
    name: '召公奭',
    dynasty: '夏商西周',
    summary: '周初重要政治人物，与周公旦共同参与周初政权建设和政治秩序稳定，并与西周分封体系的发展密切相关。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%8F%AC%E5%85%AC%E5%A5%AD%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '政治人物',
    level: 2,
    occupations: ["周初重臣"],
    related_people: [{"name":"周武王","relation":"lord_vassal","influence":75}],
    related_events: [{"name":"成康之治","role":"辅政者"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":85,"professional_1":85,"professional_2":90,"professional_3":82},
    story: {"title":"召公奭的故事","content":"召公奭，是中国历史上重要的历史人物。周初重要政治人物，与周公旦共同参与周初政权建设和政治秩序稳定，并与西周分封体系的发展密切相关。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%8F%AC%E5%85%AC%E5%A5%AD%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202052,
    name: '毕公高',
    dynasty: '夏商西周',
    summary: '周初重要宗室和大臣，参与周王朝早期政治建设，在周初政治秩序形成过程中发挥作用。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E6%AF%95%E5%85%AC%E9%AB%98%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '政治人物',
    level: 2,
    occupations: ["周初重臣"],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":85,"professional_1":85,"professional_2":90,"professional_3":82},
    story: {"title":"毕公高的故事","content":"毕公高，是中国历史上重要的历史人物。周初重要宗室和大臣，参与周王朝早期政治建设，在周初政治秩序形成过程中发挥作用。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E6%AF%95%E5%85%AC%E9%AB%98%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202053,
    name: '管叔鲜',
    dynasty: '夏商西周',
    summary: '周初重要宗室人物，被封于管。周公旦摄政期间，管叔鲜与蔡叔、霍叔以及武庚共同参与政治反抗，最终形成三监之乱。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E7%AE%A1%E5%8F%94%E9%B2%9C%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '政治人物',
    level: 2,
    occupations: ["周武王之弟"],
    related_people: [{"name":"周公旦","relation":"hostile","influence":75},{"name":"蔡叔度","relation":"alliance","influence":75},{"name":"霍叔处","relation":"alliance","influence":75}],
    related_events: [{"name":"周公东征","role":"叛乱者"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":85,"professional_1":85,"professional_2":90,"professional_3":82},
    story: {"title":"管叔鲜的故事","content":"管叔鲜，是中国历史上重要的历史人物。周初重要宗室人物，被封于管。周公旦摄政期间，管叔鲜与蔡叔、霍叔以及武庚共同参与政治反抗，最终形成三监之乱。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E7%AE%A1%E5%8F%94%E9%B2%9C%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202054,
    name: '蔡叔度',
    dynasty: '夏商西周',
    summary: '周初宗室成员，被封于蔡，与管叔鲜、霍叔处共同参与三监之乱，是周初宗室政治矛盾的重要人物。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E8%94%A1%E5%8F%94%E5%BA%A6%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '政治人物',
    level: 2,
    occupations: ["周武王之弟"],
    related_people: [{"name":"周公旦","relation":"hostile","influence":75},{"name":"管叔鲜","relation":"alliance","influence":75}],
    related_events: [{"name":"周公东征","role":"叛乱者"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":85,"professional_1":85,"professional_2":90,"professional_3":82},
    story: {"title":"蔡叔度的故事","content":"蔡叔度，是中国历史上重要的历史人物。周初宗室成员，被封于蔡，与管叔鲜、霍叔处共同参与三监之乱，是周初宗室政治矛盾的重要人物。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E8%94%A1%E5%8F%94%E5%BA%A6%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202055,
    name: '霍叔处',
    dynasty: '夏商西周',
    summary: '周初宗室成员，与管叔鲜、蔡叔度共同承担监视商遗民的任务，并卷入三监之乱，体现了周初分封与宗室政治的复杂关系。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E9%9C%8D%E5%8F%94%E5%A4%84%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '政治人物',
    level: 2,
    occupations: ["周武王之弟"],
    related_people: [{"name":"周公旦","relation":"hostile","influence":75},{"name":"管叔鲜","relation":"alliance","influence":75}],
    related_events: [{"name":"周公东征","role":"参与者"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":85,"professional_1":85,"professional_2":90,"professional_3":82},
    story: {"title":"霍叔处的故事","content":"霍叔处，是中国历史上重要的历史人物。周初宗室成员，与管叔鲜、蔡叔度共同承担监视商遗民的任务，并卷入三监之乱，体现了周初分封与宗室政治的复杂关系。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E9%9C%8D%E5%8F%94%E5%A4%84%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202056,
    name: '武庚',
    dynasty: '夏商西周',
    summary: '帝辛之子。周灭商后，武庚被留在商地管理商遗民，后来联合三监发动反周行动，是商周政治转换的重要人物。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E6%AD%A6%E5%BA%9A%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 2,
    occupations: ["商王室后裔"],
    related_people: [{"name":"周公旦","relation":"hostile","influence":75}],
    related_events: [{"name":"周公东征","role":"叛乱者"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    story: {"title":"武庚的故事","content":"武庚，是中国历史上重要的历史人物。帝辛之子。周灭商后，武庚被留在商地管理商遗民，后来联合三监发动反周行动，是商周政治转换的重要人物。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E6%AD%A6%E5%BA%9A%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202057,
    name: '康叔封',
    dynasty: '夏商西周',
    summary: '周初重要宗室人物，被封于卫，成为卫国始封君，是周初分封制度的重要代表人物之一。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%BA%B7%E5%8F%94%E5%B0%81%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 2,
    occupations: ["周武王弟、卫国始封君"],
    related_people: [{"name":"周武王","relation":"kinship","influence":75}],
    related_events: [{"name":"分封制","role":"受封者"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    story: {"title":"康叔封的故事","content":"康叔封，是中国历史上重要的历史人物。周初重要宗室人物，被封于卫，成为卫国始封君，是周初分封制度的重要代表人物之一。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%BA%B7%E5%8F%94%E5%B0%81%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202058,
    name: '伯禽',
    dynasty: '夏商西周',
    summary: '周公旦之子，被封于鲁，成为鲁国早期统治者。他的人物经历能够体现周公家族与西周分封制度之间的联系。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E4%BC%AF%E7%A6%BD%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 2,
    occupations: ["鲁国始封君"],
    related_people: [{"name":"周成王","relation":"support","influence":75},{"name":"周公旦","relation":"kinship","influence":75}],
    related_events: [{"name":"分封制","role":"受封者"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    story: {"title":"伯禽的故事","content":"伯禽，是中国历史上重要的历史人物。周公旦之子，被封于鲁，成为鲁国早期统治者。他的人物经历能够体现周公家族与西周分封制度之间的联系。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E4%BC%AF%E7%A6%BD%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202059,
    name: '尹吉甫',
    dynasty: '夏商西周',
    summary: '周宣王时期的重要军事和政治人物，传统文献和《诗经》相关材料中与周王朝北方军事行动有关，是宣王中兴时期的重要人物。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%B0%B9%E5%90%89%E7%94%AB%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '军事人物',
    level: 2,
    occupations: ["周宣王重臣"],
    related_people: [{"name":"周宣王","relation":"lord_vassal","influence":75}],
    related_events: [{"name":"宣王中兴","role":"军事将领"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":82,"professional_1":90,"professional_2":85,"professional_3":80},
    story: {"title":"尹吉甫的故事","content":"尹吉甫，是中国历史上重要的历史人物。周宣王时期的重要军事和政治人物，传统文献和《诗经》相关材料中与周王朝北方军事行动有关，是宣王中兴时期的重要人物。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%B0%B9%E5%90%89%E7%94%AB%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202060,
    name: '方叔',
    dynasty: '夏商西周',
    summary: '周宣王时期的重要将领，参与周王朝对南方地区的军事行动，是宣王时期周王朝军事活动的重要代表人物。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E6%96%B9%E5%8F%94%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '军事人物',
    level: 2,
    occupations: ["周宣王将领"],
    related_people: [{"name":"周宣王","relation":"lord_vassal","influence":75}],
    related_events: [{"name":"宣王中兴","role":"军事将领"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":82,"professional_1":90,"professional_2":85,"professional_3":80},
    story: {"title":"方叔的故事","content":"方叔，是中国历史上重要的历史人物。周宣王时期的重要将领，参与周王朝对南方地区的军事行动，是宣王时期周王朝军事活动的重要代表人物。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E6%96%B9%E5%8F%94%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202061,
    name: '召虎',
    dynasty: '夏商西周',
    summary: '周宣王时期的重要军事人物，与周王朝对淮夷等地区的军事行动有关，是宣王中兴时期军事力量的重要代表。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%8F%AC%E8%99%8E%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '军事人物',
    level: 2,
    occupations: ["周宣王将领"],
    related_people: [{"name":"周宣王","relation":"lord_vassal","influence":75}],
    related_events: [{"name":"宣王中兴","role":"军事将领"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":82,"professional_1":90,"professional_2":85,"professional_3":80},
    story: {"title":"召虎的故事","content":"召虎，是中国历史上重要的历史人物。周宣王时期的重要军事人物，与周王朝对淮夷等地区的军事行动有关，是宣王中兴时期军事力量的重要代表。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%8F%AC%E8%99%8E%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202062,
    name: '荣夷公',
    dynasty: '夏商西周',
    summary: '周厉王时期的重要政治人物，传统文献中因参与“专利”等政策而受到批评，其人物故事与周厉王时期的政治矛盾密切相关。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E8%8D%A3%E5%A4%B7%E5%85%AC%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '政治人物',
    level: 2,
    occupations: ["周厉王宠臣"],
    related_people: [{"name":"周厉王","relation":"lord_vassal","influence":75}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":85,"professional_1":85,"professional_2":90,"professional_3":82},
    story: {"title":"荣夷公的故事","content":"荣夷公，是中国历史上重要的历史人物。周厉王时期的重要政治人物，传统文献中因参与“专利”等政策而受到批评，其人物故事与周厉王时期的政治矛盾密切相关。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E8%8D%A3%E5%A4%B7%E5%85%AC%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202063,
    name: '召穆公',
    dynasty: '夏商西周',
    summary: '西周后期重要政治人物，与周厉王时期的政治危机和国人暴动有关，传统记载中体现了周王室内部不同政治力量之间的矛盾。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%8F%AC%E7%A9%86%E5%85%AC%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '政治人物',
    level: 2,
    occupations: ["周厉王时期重臣"],
    related_people: [{"name":"周厉王","relation":"lord_vassal","influence":75}],
    related_events: [{"name":"国人暴动","role":"政治参与者"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":85,"professional_1":85,"professional_2":90,"professional_3":82},
    story: {"title":"召穆公的故事","content":"召穆公，是中国历史上重要的历史人物。西周后期重要政治人物，与周厉王时期的政治危机和国人暴动有关，传统记载中体现了周王室内部不同政治力量之间的矛盾。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E5%8F%AC%E7%A9%86%E5%85%AC%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202064,
    name: '褒姒',
    dynasty: '夏商西周',
    summary: '周幽王时期的重要女性人物，传统叙事中与幽王宠爱、诸侯关系以及西周灭亡联系在一起，其中“烽火戏诸侯”等故事具有较强的后世传说色彩。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E8%A4%92%E5%A7%92%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '文化人物',
    level: 2,
    occupations: ["周幽王王后"],
    related_people: [{"name":"周幽王","relation":"kinship","influence":75}],
    related_events: [{"name":"犬戎攻周","role":"王后"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":78,"professional_1":80,"professional_2":92,"professional_3":88},
    story: {"title":"褒姒的故事","content":"褒姒，是中国历史上重要的历史人物。周幽王时期的重要女性人物，传统叙事中与幽王宠爱、诸侯关系以及西周灭亡联系在一起，其中“烽火戏诸侯”等故事具有较强的后世传说色彩。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E8%A4%92%E5%A7%92%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },
{
    id: 202065,
    name: '申侯',
    dynasty: '夏商西周',
    summary: '西周末期重要诸侯，与周幽王时期的政治冲突以及犬戎攻周密切相关，在西周灭亡的历史转折中具有重要作用。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E7%94%B3%E4%BE%AF%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4',
    birth_year: null,
    death_year: null,
    category: '统治者',
    level: 2,
    occupations: ["诸侯"],
    related_people: [{"name":"周幽王","relation":"hostile","influence":75}],
    related_events: [{"name":"犬戎攻周","role":"参与者"},{"name":"西周灭亡","role":"相关诸侯"}],
    influence: 80,
    dimension_scores: {"historical_influence":80,"relation_activity":88,"professional_1":92,"professional_2":85,"professional_3":90},
    story: {"title":"申侯的故事","content":"申侯，是中国历史上重要的历史人物。西周末期重要诸侯，与周幽王时期的政治冲突以及犬戎攻周密切相关，在西周灭亡的历史转折中具有重要作用。","image_url":"https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20figure%20%E7%94%B3%E4%BE%AF%20traditional%20ink%20painting%20style%20portrait&image_size=portrait_3_4"},
    narrative_relations: {"nodes":[],"edges":[]}
  },

// --- 夏商西周事件 (18个) ---
{
    id: 204001,
    name: '太康失国',
    dynasty: '夏商西周',
    start_year: -2000,
    end_year: -2000,
    summary: '夏王太康统治时期荒废政事，长期外出狩猎，相传后羿因此逐渐掌握夏朝政治权力，太康失去王位。',
    event_type: '政治事件',
    related_persons: ["太康","后羿"],
    significance: '反映早期夏王朝内部权力不稳以及王室与地方势力之间的矛盾。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20event%20%E5%A4%AA%E5%BA%B7%E5%A4%B1%E5%9B%BD%20traditional%20ink%20painting%20style&image_size=landscape_16_9',
    one_sentence: '夏王太康统治时期荒废政事，长期外出狩猎，相传后羿因此逐渐掌握夏朝政治权力，太康失去王位。',
    person_groups: {"leaders":[{"name":"后羿","role":"政权掌握者"}],"participants":[],"opponents":[{"name":"太康","role":"失势者"}],"affected":[]},
    narratives: [],
    background: {},
    impacts: [],
    chain: [],
    related_events: [],
    person_relations: [{"source":"太康","target":"后羿","type":"hostile","desc":"太康失政后，后羿逐渐掌握夏朝政治权力。"}]
  },
{
    id: 204002,
    name: '少康中兴',
    dynasty: '夏商西周',
    start_year: -1900,
    end_year: -1900,
    summary: '少康在夏王室势力衰落后重新积蓄力量，在伯靡等人的支持下击败寒浞势力，恢复夏王朝统治。',
    event_type: '政治事件',
    related_persons: ["少康","寒浞","伯靡","女艾"],
    significance: '夏王朝重新恢复统治，是夏代历史叙事中重要的复兴阶段。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20event%20%E5%B0%91%E5%BA%B7%E4%B8%AD%E5%85%B4%20traditional%20ink%20painting%20style&image_size=landscape_16_9',
    one_sentence: '少康在夏王室势力衰落后重新积蓄力量，在伯靡等人的支持下击败寒浞势力，恢复夏王朝统治。',
    person_groups: {"leaders":[{"name":"少康","role":"中兴者"}],"participants":[{"name":"伯靡","role":"支持者"},{"name":"女艾","role":"谋臣"}],"opponents":[{"name":"寒浞","role":"对立者"}],"affected":[]},
    narratives: [],
    background: {},
    impacts: [],
    chain: [],
    related_events: [],
    person_relations: [{"source":"少康","target":"寒浞","type":"hostile","desc":"少康复国过程中与寒浞势力形成直接对立。"},{"source":"少康","target":"伯靡","type":"lord_vassal","desc":"伯靡传统上被认为支持少康复国。"},{"source":"少康","target":"女艾","type":"lord_vassal","desc":"女艾传统上被认为参与少康复国行动。"}]
  },
{
    id: 204003,
    name: '夏桀暴政',
    dynasty: '夏商西周',
    start_year: -1700,
    end_year: -1700,
    summary: '夏桀统治时期，传统文献将其描述为政治腐败、奢侈暴虐，王朝内部矛盾和统治危机不断加深。',
    event_type: '政治事件',
    related_persons: ["夏桀","关龙逢","妺喜"],
    significance: '加剧夏王朝统治危机，为商汤灭夏和夏商王朝更替创造条件。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20event%20%E5%A4%8F%E6%A1%80%E6%9A%B4%E6%94%BF%20traditional%20ink%20painting%20style&image_size=landscape_16_9',
    one_sentence: '夏桀统治时期，传统文献将其描述为政治腐败、奢侈暴虐，王朝内部矛盾和统治危机不断加深。',
    person_groups: {"leaders":[{"name":"夏桀","role":"统治者"}],"participants":[{"name":"关龙逢","role":"进谏者"}],"opponents":[],"affected":[{"name":"妺喜","role":"宫廷人物"}]},
    narratives: [],
    background: {},
    impacts: [],
    chain: [],
    related_events: [],
    person_relations: [{"source":"夏桀","target":"关龙逢","type":"lord_vassal","desc":"关龙逢传统上因直谏夏桀而遭杀害。"},{"source":"夏桀","target":"妺喜","type":"support","desc":"传统叙事中妺喜与夏桀宫廷生活密切相关。"}]
  },
{
    id: 204004,
    name: '商汤灭夏',
    dynasty: '夏商西周',
    start_year: -1600,
    end_year: -1600,
    summary: '商汤联合诸侯讨伐夏桀，在鸣条一带击败夏军，结束夏王朝统治并建立商朝。',
    event_type: '战争军事',
    related_persons: ["商汤","夏桀","伊尹","仲虺"],
    significance: '完成夏商王朝更替，是中国早期王朝更替的重要历史节点。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20event%20%E5%95%86%E6%B1%A4%E7%81%AD%E5%A4%8F%20traditional%20ink%20painting%20style&image_size=landscape_16_9',
    one_sentence: '商汤联合诸侯讨伐夏桀，在鸣条一带击败夏军，结束夏王朝统治并建立商朝。',
    person_groups: {"leaders":[{"name":"商汤","role":"胜利方"}],"participants":[{"name":"伊尹","role":"辅政者"},{"name":"仲虺","role":"辅政者"}],"opponents":[{"name":"夏桀","role":"失败方"}],"affected":[]},
    narratives: [],
    background: {},
    impacts: [],
    chain: [],
    related_events: [],
    person_relations: [{"source":"商汤","target":"夏桀","type":"hostile","desc":"商汤灭夏过程中双方成为王朝更替的直接对手。"},{"source":"商汤","target":"伊尹","type":"lord_vassal","desc":"伊尹是商汤灭夏及商初政治建设的重要辅臣。"},{"source":"商汤","target":"仲虺","type":"lord_vassal","desc":"仲虺是商汤时期的重要辅臣。"}]
  },
{
    id: 204005,
    name: '盘庚迁殷',
    dynasty: '夏商西周',
    start_year: -1300,
    end_year: -1300,
    summary: '商王盘庚将都城迁至殷，并通过迁都重新整合王权和政治资源。',
    event_type: '政治事件',
    related_persons: ["盘庚"],
    significance: '殷成为商王朝后期长期政治中心，商代因此又被称为殷商。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20event%20%E7%9B%98%E5%BA%9A%E8%BF%81%E6%AE%B7%20traditional%20ink%20painting%20style&image_size=landscape_16_9',
    one_sentence: '商王盘庚将都城迁至殷，并通过迁都重新整合王权和政治资源。',
    person_groups: {"leaders":[{"name":"盘庚","role":"主导者"}],"participants":[],"opponents":[],"affected":[]},
    narratives: [],
    background: {},
    impacts: [],
    chain: [],
    related_events: [],
    person_relations: []
  },
{
    id: 204006,
    name: '武丁中兴',
    dynasty: '夏商西周',
    start_year: -1300,
    end_year: -1300,
    summary: '武丁时期任用傅说、甘盘等重要臣僚，加强王权并积极开展对外军事行动，商王朝国力得到明显发展。',
    event_type: '盛世发展',
    related_persons: ["武丁","妇好","傅说","甘盘"],
    significance: '推动商王朝政治、军事和社会发展，是商代后期的重要繁荣阶段。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20event%20%E6%AD%A6%E4%B8%81%E4%B8%AD%E5%85%B4%20traditional%20ink%20painting%20style&image_size=landscape_16_9',
    one_sentence: '武丁时期任用傅说、甘盘等重要臣僚，加强王权并积极开展对外军事行动，商王朝国力得到明显发展。',
    person_groups: {"leaders":[{"name":"武丁","role":"主导者"}],"participants":[{"name":"妇好","role":"重要人物"},{"name":"傅说","role":"辅政者"},{"name":"甘盘","role":"辅政者"}],"opponents":[],"affected":[]},
    narratives: [],
    background: {},
    impacts: [],
    chain: [],
    related_events: [],
    person_relations: [{"source":"武丁","target":"妇好","type":"kinship","desc":"妇好是武丁的重要王后，同时具有独立的政治军事影响。"},{"source":"武丁","target":"傅说","type":"lord_vassal","desc":"武丁任用傅说为重要辅臣，傅说成为武丁中兴的重要人物。"},{"source":"武丁","target":"甘盘","type":"lord_vassal","desc":"甘盘是武丁时期的重要辅臣。"},{"source":"妇好","target":"傅说","type":"friend","desc":"二人均与武丁时期商王朝政治体系有关。"}]
  },
{
    id: 204007,
    name: '妇好征伐',
    dynasty: '夏商西周',
    start_year: -1300,
    end_year: -1300,
    summary: '妇好是武丁时期重要王后和军事人物，甲骨文记录了她参与多次对外战争和祭祀活动。',
    event_type: '战争军事',
    related_persons: ["妇好","武丁"],
    significance: '展现商代王室军事体系以及女性参与政治、军事活动的历史面貌。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20event%20%E5%A6%87%E5%A5%BD%E5%BE%81%E4%BC%90%20traditional%20ink%20painting%20style&image_size=landscape_16_9',
    one_sentence: '妇好是武丁时期重要王后和军事人物，甲骨文记录了她参与多次对外战争和祭祀活动。',
    person_groups: {"leaders":[{"name":"武丁","role":"统治者"}],"participants":[{"name":"妇好","role":"军事人物"}],"opponents":[],"affected":[]},
    narratives: [],
    background: {},
    impacts: [],
    chain: [],
    related_events: [],
    person_relations: [{"source":"武丁","target":"妇好","type":"kinship","desc":"妇好是武丁的重要王后，同时具有独立的政治军事影响。"}]
  },
{
    id: 204008,
    name: '商王对外征伐',
    dynasty: '夏商西周',
    start_year: -1300,
    end_year: -1300,
    summary: '商王朝持续对周边方国和部族发动军事行动，以扩大和巩固王朝的政治影响。',
    event_type: '战争军事',
    related_persons: ["武丁"],
    significance: '体现商代王权与方国之间的关系以及以战争、祭祀为重要特征的政治文化。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20event%20%E5%95%86%E7%8E%8B%E5%AF%B9%E5%A4%96%E5%BE%81%E4%BC%90%20traditional%20ink%20painting%20style&image_size=landscape_16_9',
    one_sentence: '商王朝持续对周边方国和部族发动军事行动，以扩大和巩固王朝的政治影响。',
    person_groups: {"leaders":[{"name":"武丁","role":"统治者"}],"participants":[],"opponents":[],"affected":[]},
    narratives: [],
    background: {},
    impacts: [],
    chain: [],
    related_events: [],
    person_relations: []
  },
{
    id: 204009,
    name: '商末政治危机',
    dynasty: '夏商西周',
    start_year: -1100,
    end_year: -1100,
    summary: '帝辛时期商王权威受到周边势力挑战，内部政治矛盾逐渐加深，商王朝统治基础不断削弱。',
    event_type: '政治事件',
    related_persons: ["帝辛","比干","箕子","微子启"],
    significance: '为周人崛起以及最终灭商创造了政治条件。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20event%20%E5%95%86%E6%9C%AB%E6%94%BF%E6%B2%BB%E5%8D%B1%E6%9C%BA%20traditional%20ink%20painting%20style&image_size=landscape_16_9',
    one_sentence: '帝辛时期商王权威受到周边势力挑战，内部政治矛盾逐渐加深，商王朝统治基础不断削弱。',
    person_groups: {"leaders":[{"name":"帝辛","role":"统治者"}],"participants":[{"name":"比干","role":"进谏者"}],"opponents":[],"affected":[{"name":"箕子","role":"王室人物"},{"name":"微子启","role":"王室人物"}]},
    narratives: [],
    background: {},
    impacts: [],
    chain: [],
    related_events: [],
    person_relations: [{"source":"帝辛","target":"比干","type":"kinship","desc":"比干属于商王室成员，传统上因劝谏帝辛而死。"},{"source":"帝辛","target":"箕子","type":"support","desc":"箕子属于商王室成员，与帝辛时期政治危机密切相关。"},{"source":"帝辛","target":"微子启","type":"kinship","desc":"微子启与帝辛均属于商王室成员。"},{"source":"箕子","target":"比干","type":"kinship","desc":"二人均属于商王室贵族。"}]
  },
{
    id: 204010,
    name: '牧野之战',
    dynasty: '夏商西周',
    start_year: -1046,
    end_year: -1046,
    summary: '周武王率诸侯联军与商军在牧野决战，商军阵营发生动摇，周军取得决定性胜利。',
    event_type: '战争军事',
    related_persons: ["周武王","帝辛","姜子牙","周公旦"],
    significance: '直接导致商王朝覆亡，为西周建立奠定基础。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20event%20%E7%89%A7%E9%87%8E%E4%B9%8B%E6%88%98%20traditional%20ink%20painting%20style&image_size=landscape_16_9',
    one_sentence: '周武王率诸侯联军与商军在牧野决战，商军阵营发生动摇，周军取得决定性胜利。',
    person_groups: {"leaders":[{"name":"周武王","role":"胜利方"}],"participants":[{"name":"姜子牙","role":"重要将领"}],"opponents":[{"name":"帝辛","role":"失败方"}],"affected":[{"name":"周公旦","role":"宗室成员"}]},
    narratives: [],
    background: {},
    impacts: [],
    chain: [],
    related_events: [],
    person_relations: [{"source":"周武王","target":"周公旦","type":"kinship","desc":"周公旦是周武王的重要弟弟和辅臣。"},{"source":"周武王","target":"姜子牙","type":"lord_vassal","desc":"姜子牙辅佐周武王完成灭商战争。"}]
  },
{
    id: 204011,
    name: '周公东征',
    dynasty: '夏商西周',
    start_year: -1040,
    end_year: -1040,
    summary: '周武王去世后，周公旦辅佐周成王，平定武庚及管叔鲜、蔡叔度、霍叔处等势力的叛乱，巩固西周统治。',
    event_type: '战争军事',
    related_persons: ["周公旦","武庚","管叔鲜","蔡叔度","霍叔处"],
    significance: '巩固西周早期政权，加强周王朝对东方地区的控制。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20event%20%E5%91%A8%E5%85%AC%E4%B8%9C%E5%BE%81%20traditional%20ink%20painting%20style&image_size=landscape_16_9',
    one_sentence: '周武王去世后，周公旦辅佐周成王，平定武庚及管叔鲜、蔡叔度、霍叔处等势力的叛乱，巩固西周统治。',
    person_groups: {"leaders":[{"name":"周公旦","role":"主导者"}],"participants":[{"name":"霍叔处","role":"参与者"}],"opponents":[{"name":"武庚","role":"叛乱者"},{"name":"管叔鲜","role":"叛乱者"},{"name":"蔡叔度","role":"叛乱者"}],"affected":[]},
    narratives: [],
    background: {},
    impacts: [],
    chain: [],
    related_events: [],
    person_relations: [{"source":"周公旦","target":"管叔鲜","type":"hostile","desc":"管叔鲜参与三监之乱，与周公旦形成政治对立。"},{"source":"周公旦","target":"蔡叔度","type":"hostile","desc":"蔡叔度参与三监之乱，与周公旦形成政治对立。"},{"source":"周公旦","target":"霍叔处","type":"hostile","desc":"霍叔处参与三监相关政治行动，与周公旦形成政治对立。"},{"source":"周公旦","target":"武庚","type":"hostile","desc":"武庚参与反周行动，周公旦率军平定相关叛乱。"},{"source":"管叔鲜","target":"蔡叔度","type":"alliance","desc":"管叔鲜与蔡叔度共同参与三监之乱。"}]
  },
{
    id: 204012,
    name: '成康之治',
    dynasty: '夏商西周',
    start_year: -1100,
    end_year: -1100,
    summary: '周成王、周康王时期政治秩序逐渐稳定，周王朝统治得到进一步巩固，后世称为“成康之治”。',
    event_type: '盛世发展',
    related_persons: ["周成王","周康王","周公旦","召公奭"],
    significance: '成为西周早期政治稳定和社会发展的代表时期。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20event%20%E6%88%90%E5%BA%B7%E4%B9%8B%E6%B2%BB%20traditional%20ink%20painting%20style&image_size=landscape_16_9',
    one_sentence: '周成王、周康王时期政治秩序逐渐稳定，周王朝统治得到进一步巩固，后世称为“成康之治”。',
    person_groups: {"leaders":[{"name":"周成王","role":"统治者"},{"name":"周康王","role":"统治者"}],"participants":[{"name":"周公旦","role":"辅政者"},{"name":"召公奭","role":"辅政者"}],"opponents":[],"affected":[]},
    narratives: [],
    background: {},
    impacts: [],
    chain: [],
    related_events: [],
    person_relations: [{"source":"周成王","target":"周公旦","type":"lord_vassal","desc":"周成王年幼时期由周公旦辅政。"},{"source":"周成王","target":"周康王","type":"support","desc":"周康王继承周成王的王位，延续西周早期政治秩序。"}]
  },
{
    id: 204013,
    name: '制礼作乐',
    dynasty: '夏商西周',
    start_year: -1100,
    end_year: -1100,
    summary: '周公旦等人在周初政治建设过程中完善礼乐秩序，将宗法、等级与政治秩序结合起来。',
    event_type: '制度文化',
    related_persons: ["周公旦","周成王"],
    significance: '对中国古代礼制、政治文化和社会秩序产生长期影响。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20event%20%E5%88%B6%E7%A4%BC%E4%BD%9C%E4%B9%90%20traditional%20ink%20painting%20style&image_size=landscape_16_9',
    one_sentence: '周公旦等人在周初政治建设过程中完善礼乐秩序，将宗法、等级与政治秩序结合起来。',
    person_groups: {"leaders":[{"name":"周成王","role":"统治者"}],"participants":[{"name":"周公旦","role":"制度建设者"}],"opponents":[],"affected":[]},
    narratives: [],
    background: {},
    impacts: [],
    chain: [],
    related_events: [],
    person_relations: [{"source":"周成王","target":"周公旦","type":"lord_vassal","desc":"周成王年幼时期由周公旦辅政。"}]
  },
{
    id: 204014,
    name: '分封制',
    dynasty: '夏商西周',
    start_year: -1100,
    end_year: -1100,
    summary: '西周建立后，周王室将宗室、功臣等分封到各地建立诸侯国，形成周王室与诸侯之间的政治秩序。',
    event_type: '制度建设',
    related_persons: ["周武王","周公旦","康叔封","伯禽"],
    significance: '成为西周政治制度的重要组成部分，对后世政治结构产生深远影响。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20event%20%E5%88%86%E5%B0%81%E5%88%B6%20traditional%20ink%20painting%20style&image_size=landscape_16_9',
    one_sentence: '西周建立后，周王室将宗室、功臣等分封到各地建立诸侯国，形成周王室与诸侯之间的政治秩序。',
    person_groups: {"leaders":[{"name":"周武王","role":"制度建立者"}],"participants":[{"name":"周公旦","role":"制度推动者"}],"opponents":[],"affected":[{"name":"康叔封","role":"受封者"},{"name":"伯禽","role":"受封者"}]},
    narratives: [],
    background: {},
    impacts: [],
    chain: [],
    related_events: [],
    person_relations: [{"source":"周武王","target":"周公旦","type":"kinship","desc":"周公旦是周武王的重要弟弟和辅臣。"},{"source":"周公旦","target":"伯禽","type":"kinship","desc":"伯禽为周公旦之子，后来受封于鲁。"},{"source":"周武王","target":"康叔封","type":"kinship","desc":"康叔封为周武王之弟，后被分封于卫。"}]
  },
{
    id: 204015,
    name: '国人暴动',
    dynasty: '夏商西周',
    start_year: -841,
    end_year: -841,
    summary: '周厉王统治时期实行严厉的政治和经济政策，引发镐京国人不满并爆发暴动，周厉王被迫出逃。',
    event_type: '政治事件',
    related_persons: ["周厉王","召穆公"],
    significance: '周王室权威受到重大冲击，是西周后期政治危机的重要节点。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20event%20%E5%9B%BD%E4%BA%BA%E6%9A%B4%E5%8A%A8%20traditional%20ink%20painting%20style&image_size=landscape_16_9',
    one_sentence: '周厉王统治时期实行严厉的政治和经济政策，引发镐京国人不满并爆发暴动，周厉王被迫出逃。',
    person_groups: {"leaders":[],"participants":[],"opponents":[{"name":"周厉王","role":"被驱逐者"}],"affected":[{"name":"召穆公","role":"政治参与者"}]},
    narratives: [],
    background: {},
    impacts: [],
    chain: [],
    related_events: [],
    person_relations: [{"source":"周厉王","target":"召穆公","type":"lord_vassal","desc":"召穆公属于周厉王时期的重要政治人物。"}]
  },
{
    id: 204016,
    name: '宣王中兴',
    dynasty: '夏商西周',
    start_year: -827,
    end_year: -827,
    summary: '周宣王即位后整顿政治与军事，任用尹吉甫、方叔、召虎等人物处理周边局势，使周王室一度恢复统治力量。',
    event_type: '政治事件',
    related_persons: ["周宣王","尹吉甫","方叔","召虎"],
    significance: '西周后期出现短暂复兴，但未能从根本上扭转周王室衰落趋势。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20event%20%E5%AE%A3%E7%8E%8B%E4%B8%AD%E5%85%B4%20traditional%20ink%20painting%20style&image_size=landscape_16_9',
    one_sentence: '周宣王即位后整顿政治与军事，任用尹吉甫、方叔、召虎等人物处理周边局势，使周王室一度恢复统治力量。',
    person_groups: {"leaders":[{"name":"周宣王","role":"主导者"}],"participants":[{"name":"尹吉甫","role":"军事将领"},{"name":"方叔","role":"军事将领"},{"name":"召虎","role":"军事将领"}],"opponents":[],"affected":[]},
    narratives: [],
    background: {},
    impacts: [],
    chain: [],
    related_events: [],
    person_relations: [{"source":"周宣王","target":"尹吉甫","type":"lord_vassal","desc":"尹吉甫是周宣王时期的重要军事和政治人物。"},{"source":"周宣王","target":"方叔","type":"lord_vassal","desc":"方叔是周宣王时期重要军事将领。"},{"source":"周宣王","target":"召虎","type":"lord_vassal","desc":"召虎是周宣王时期重要军事人物。"},{"source":"周宣王","target":"尹吉甫","type":"lord_vassal","desc":"尹吉甫参与周宣王时期的军事行动并辅佐周王。"},{"source":"周宣王","target":"方叔","type":"lord_vassal","desc":"方叔参与周宣王时期南方军事行动。"}]
  },
{
    id: 204017,
    name: '犬戎攻周',
    dynasty: '夏商西周',
    start_year: -771,
    end_year: -771,
    summary: '西周末年，周幽王时期政治局势恶化，犬戎等势力攻入镐京，周幽王在骊山附近被杀。',
    event_type: '战争军事',
    related_persons: ["周幽王","褒姒","申侯"],
    significance: '周王室失去关中政治中心，西周统治走向终结。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20event%20%E7%8A%AC%E6%88%8E%E6%94%BB%E5%91%A8%20traditional%20ink%20painting%20style&image_size=landscape_16_9',
    one_sentence: '西周末年，周幽王时期政治局势恶化，犬戎等势力攻入镐京，周幽王在骊山附近被杀。',
    person_groups: {"leaders":[],"participants":[{"name":"申侯","role":"参与者"}],"opponents":[{"name":"周幽王","role":"失败方"}],"affected":[{"name":"褒姒","role":"王后"}]},
    narratives: [],
    background: {},
    impacts: [],
    chain: [],
    related_events: [],
    person_relations: [{"source":"周幽王","target":"褒姒","type":"kinship","desc":"褒姒为周幽王王后。"},{"source":"周幽王","target":"申侯","type":"hostile","desc":"申侯与周幽王之间存在政治冲突，并参与西周末年政局变化。"}]
  },
{
    id: 204018,
    name: '西周灭亡',
    dynasty: '夏商西周',
    start_year: -771,
    end_year: -771,
    summary: '犬戎攻破镐京后，周王室失去西部政治中心，周平王随后迁都洛邑，西周结束。',
    event_type: '王朝灭亡',
    related_persons: ["周幽王","申侯"],
    significance: '标志西周结束和东周时代开始，是中国古代历史重要分期节点。',
    image_url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20historical%20event%20%E8%A5%BF%E5%91%A8%E7%81%AD%E4%BA%A1%20traditional%20ink%20painting%20style&image_size=landscape_16_9',
    one_sentence: '犬戎攻破镐京后，周王室失去西部政治中心，周平王随后迁都洛邑，西周结束。',
    person_groups: {"leaders":[],"participants":[],"opponents":[{"name":"周幽王","role":"末代君主"}],"affected":[{"name":"申侯","role":"相关诸侯"}]},
    narratives: [],
    background: {},
    impacts: [],
    chain: [],
    related_events: [],
    person_relations: [{"source":"周幽王","target":"申侯","type":"hostile","desc":"申侯与周幽王之间存在政治冲突，并参与西周末年政局变化。"}]
  },

// --- 夏商西周关键词 (20个) ---
// 添加到 Dynasty.vue 的 dynastyKeywords computed 中:
// '夏商西周': [
  {
    "name": "王朝更替",
    "value": 100,
    "category": "era",
    "desc": "王朝更替是夏商西周时期的重要概念。"
  },
  {
    "name": "青铜文明",
    "value": 96,
    "category": "era",
    "desc": "青铜文明是夏商西周时期的重要概念。"
  },
  {
    "name": "华夏文明",
    "value": 93,
    "category": "era",
    "desc": "华夏文明是夏商西周时期的重要概念。"
  },
  {
    "name": "周公旦",
    "value": 91,
    "category": "person",
    "desc": "周公旦是夏商西周时期的重要概念。"
  },
  {
    "name": "周武王",
    "value": 89,
    "category": "person",
    "desc": "周武王是夏商西周时期的重要概念。"
  },
  {
    "name": "商汤",
    "value": 87,
    "category": "person",
    "desc": "商汤是夏商西周时期的重要概念。"
  },
  {
    "name": "周文王",
    "value": 85,
    "category": "person",
    "desc": "周文王是夏商西周时期的重要概念。"
  },
  {
    "name": "武丁",
    "value": 81,
    "category": "person",
    "desc": "武丁是夏商西周时期的重要概念。"
  },
  {
    "name": "妇好",
    "value": 77,
    "category": "person",
    "desc": "妇好是夏商西周时期的重要概念。"
  },
  {
    "name": "牧野之战",
    "value": 88,
    "category": "event",
    "desc": "牧野之战是夏商西周时期的重要概念。"
  },
  {
    "name": "商汤灭夏",
    "value": 84,
    "category": "event",
    "desc": "商汤灭夏是夏商西周时期的重要概念。"
  },
  {
    "name": "成康之治",
    "value": 72,
    "category": "event",
    "desc": "成康之治是夏商西周时期的重要概念。"
  },
  {
    "name": "盘庚迁殷",
    "value": 67,
    "category": "event",
    "desc": "盘庚迁殷是夏商西周时期的重要概念。"
  },
  {
    "name": "西周灭亡",
    "value": 78,
    "category": "event",
    "desc": "西周灭亡是夏商西周时期的重要概念。"
  },
  {
    "name": "国人暴动",
    "value": 63,
    "category": "event",
    "desc": "国人暴动是夏商西周时期的重要概念。"
  },
  {
    "name": "分封制",
    "value": 86,
    "category": "civilization",
    "desc": "分封制是夏商西周时期的重要概念。"
  },
  {
    "name": "礼乐制度",
    "value": 80,
    "category": "civilization",
    "desc": "礼乐制度是夏商西周时期的重要概念。"
  },
  {
    "name": "甲骨文",
    "value": 83,
    "category": "civilization",
    "desc": "甲骨文是夏商西周时期的重要概念。"
  },
  {
    "name": "宗法制",
    "value": 70,
    "category": "civilization",
    "desc": "宗法制是夏商西周时期的重要概念。"
  },
  {
    "name": "天命观",
    "value": 61,
    "category": "civilization",
    "desc": "天命观是夏商西周时期的重要概念。"
  }
],

// --- 统计数据更新 ---
// 在 dynastyStatistics.byDynasty 中添加:
// { name: '夏商西周', value: 100, rate: 100, person_count: 65, event_count: 18, work_count: 0, relation_count: 58 },

